name: JavaFX CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, fedora-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'maven'

      - name: Install JavaFX (Fedora)
        if: runner.os == 'Linux'
        run: |
          sudo dnf install -y java-22-openjdk-openjfx
          echo "MAVEN_OPTS=--module-path /usr/lib/jvm/java-22-openjdk/lib --add-modules javafx.controls,javafx.fxml,javafx.media,javafx.graphics,javafx.base" >> $GITHUB_ENV

      - name: Install JavaFX (Windows)
        if: runner.os == 'Windows'
        run: |
          $JAVAFX_URL = "https://download2.gluonhq.com/openjfx/23/openjfx-23_windows-x64_bin-sdk.zip"
          Invoke-WebRequest -Uri $JAVAFX_URL -OutFile javafx.zip
          Expand-Archive -Path javafx.zip -DestinationPath $env:GITHUB_WORKSPACE/javafx
          echo "MAVEN_OPTS=--module-path $env:GITHUB_WORKSPACE/javafx/javafx-sdk-23/lib --add-modules javafx.controls,javafx.fxml,javafx.media,javafx.graphics,javafx.base" >> $env:GITHUB_ENV

      - name: Verify Java and Maven versions
        run: |
          java -version
          mvn -version

      - name: Build and Test with Maven
        run: mvn clean test