name: JavaFX CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, fedora-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'maven'

      - name: Install JavaFX (Fedora)
        if: runner.os == 'Linux'
        run: |
          sudo dnf install -y java-22-openjdk-openjfx
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))" >> $GITHUB_ENV

      - name: Install JavaFX (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install openjfx
          echo "JAVA_HOME=${JAVA_HOME}" >> $env:GITHUB_ENV

      - name: Verify Java and Maven versions
        run: |
          java -version
          mvn -version

      - name: Build and Test with Maven
        run: mvn clean test